name: CI

on:
  push:
    paths:
      - '.github/workflows/**'
      - '**/*.cs'
      - '**/*.csproj'
      - 'manifest.json'
      - 'DalamudPackager.targets'
      - 'Local.props.example'
      - 'README.md'
  pull_request:
    paths:
      - '**/*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore ./XIVSubmarinesReturn.csproj
        working-directory: ${{ github.workspace }}
      - name: Build (Release x64)
        run: dotnet build ./XIVSubmarinesReturn.csproj -c Release -p:Platform=x64 -p:SkipPack=true --nologo
        working-directory: ${{ github.workspace }}

