from __future__ import annotations

import json
from importlib.resources import files

_DATA = json.loads(files(__package__).joinpath("data.json").read_text(encoding="utf-8"))

TARGETS = _DATA["TARGETS"]
ACTIONS = _DATA["ACTIONS"]
SELF_PRONOUNS = _DATA["SELF_PRONOUNS"]
ROLES = _DATA["ROLES"]
POWERS = _DATA["POWERS"]
RESULTS = _DATA["RESULTS"]
GREETINGS = _DATA["GREETINGS"]
SKILLS = _DATA["SKILLS"]
WARNINGS = _DATA["WARNINGS"]
ADVERBS = _DATA["ADVERBS"]
CLAIMS = _DATA["CLAIMS"]
FILLERS = _DATA["FILLERS"]
IMPERATIVES = _DATA["IMPERATIVES"]
POSTFIXES = _DATA["POSTFIXES"]
EVALUATIONS = _DATA["EVALUATIONS"]
CONTRASTS = _DATA["CONTRASTS"]
BOASTS = _DATA["BOASTS"]
ITEMS = _DATA["ITEMS"]
RARITIES = _DATA["RARITIES"]
VERBS = _DATA["VERBS"]
EMOJIS = _DATA["EMOJIS"]
ENGLISH = _DATA["ENGLISH"]
KATAKANA = _DATA["KATAKANA"]
EXCUSES = _DATA["EXCUSES"]
POLITE = _DATA["POLITE"]
GAME_TERMS = _DATA["GAME_TERMS"]
OPINIONS = _DATA["OPINIONS"]
DIFFERENTS = _DATA["DIFFERENTS"]
TAILS = _DATA["TAILS"]
ELLIPSIS = _DATA["ELLIPSIS"]
