name: Python Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    name: Unit tests (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (ff14-submarines)
        run: |
          python -m pip install --upgrade pip
          if [ -f "apps/ff14-submarines/requirements.txt" ]; then python -m pip install -r apps/ff14-submarines/requirements.txt; fi
        shell: bash

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test*.py" -v
